### ISSUE TITLE
Copyright issues?

### ISSUE THREAD

**Issue by mox-mox** [andysworkshop/stm32plus#117]
Hi,

I'm considering using stm32plus for a university project, but when I just looked over one of the linker scripts, I noticed the following lines there:

**  (c)Copyright Atollic AB.
**  You may use this file as-is or modify it according to the needs of your
**  project. Distribution of this file (unmodified or modified) is not
**  permitted. Atollic AB permit registered Atollic TrueSTUDIO(R) users the
**  rights to distribute the assembled, compiled & linked contents of this
**  file as part of an application binary file, provided that it is built
**  using the Atollic TrueSTUDIO(R) toolchain.

So, is it safe to use these files, or should I switch them for some others, if I intend to pass my work over to other people?

regards,
mox

p.S.> I really like the clean, structured look of the lib (compared to the STM-provided ones...) :)

**Comment by andysworkshop** [comment]
The only files affected by that license are the linker scripts used by the example programs so anything you build yourself using the library will be unaffected.

I've been meaning to replace those scripts with home-grown versions because the example programs have a very simple memory layout and don't require much of the additional stuff.
